name: example-environment
channels:
  - conda-forge
dependencies:
  - cartopy
  - python>=3.6
  - notebook
  - rise
  - matplotlib
  - numpy
  - scikit-image
  - folium
  - geopandas
  - fiona
  - shapely
  - iris
  - xarray
  - docutils
  - pyproj
  - pytest
  - requests
  - paramiko
  - astropy
  - h5py
  - joblib
  - scipy
  - GitPython
  - ipython
  - recommonmark
  - descartes
  
